protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		if(isset(Yii::app()->user->type) && Yii::app()->user->type === 'social_user')
			$redirectUrl = Yii::app()->session['lastUrl'];

		else
			$redirectUrl = Yii::app()->homeUrl;

		Yii::app()->user->logout();

		$this->redirect($redirectUrl);
	}

	public function actionMap()
	{
		$this->render('map',array(
			'mapOptions' => array(
				'id' => 'map',
				'defaultUI' => json_encode(false),
				'addMarkers' => json_encode(array('enabled' => true,'limit' => 4,'deleteOnClick' => true,'centerOnClick' => true,'traceRoute' => true)),
				'markersData' => json_encode(array(
					'abc' => array(
						'title' => 'hola',
						'x' => '-25.352393',
						'y' => '131.044923',
						'message' => 'que paso!?',
						'image' => Yii::app()->getBaseUrl(true).'/images/site/marker2.png',
						'shape' => array('coord' => array(14,32,17,32,18,18,24,11,24,6,19,0,12,0,7,6,7,11,13,17,14,32),'type' => 'poly')
					),
					'def' => array(
						'title' => 'otro hola',
						'x' => '-25.363882',
						'y' => '131.044922',
						'message' => 'que pasaaaaaaaoooooooo!!',
						'image' => Yii::app()->getBaseUrl(true).'/images/site/marker1.png',
						'shape' => array('coord' => array(13,32,26,20,26,2,0,1,0,20,13,32),'type' => 'poly')
					)
				))
			),
		));
	}

	public function actionSocial()
	{
		$this->render('social');
	}

	public function actionOrder_Array()
	{
		$data = array(array('valor' => 10),array('valor' => 50),array('valor' => 75),array('valor' => 5),array('valor' => 100));
		$dataSorted = ArrayTools::ORDER_ARRAY($data,'valor');
		$dataSortedInv = ArrayTools::ORDER_ARRAY($data,'valor',true);
		$this->render('order_array',array('data' => $data,'dataSorted' => $dataSorted,'dataSortedInv' => $dataSortedInv));
	}

	public function actionFile_uploader()
	{
		$uploaderConfig = array();
		$uploaderConfig['id'] = 'fileupload';
		$uploaderConfig['id_js'] = '#'.$uploaderConfig['id'];
		$uploaderConfig['id_progress'] = 'progress';
		$uploaderConfig['id_js_progress'] = '#'.$uploaderConfig['id_progress'];

		$this->render('file_uploader',array(
			'uploaderConfig' => $uploaderConfig
		));
	}

	public function actionUpload()
	{
		$ds = DIRECTORY_SEPARATOR;
		$storeFolder = 'uploads';
		$fileMaxSize = 10485760; //10MiB
		$fileMaxSizeString = (string)($fileMaxSize/1024/1024).' MiB';

		if (!empty($_FILES)) {

			if($_FILES['file']['type'] != image_type_to_mime_type(IMAGETYPE_JPEG) && $_FILES['file']['type'] != image_type_to_mime_type(IMAGETYPE_PNG))
				throw new CHttpException(415, 'Unsupported Media Type. ('.$_FILES['file']['type'].')');

			if($_FILES['file']['size'] > $fileMaxSize)
				throw new CHttpException(415, 'The file is too large to upload (Max '.$fileMaxSizeString.').');

			$tempFile = $_FILES['file']['tmp_name'];
			$targetPath = Yii::getPathOfAlias('local') . $ds. $storeFolder . $ds;
			$targetFile =  $targetPath. $_FILES['file']['name'];
			if(!file_exists($targetFile))
				move_uploaded_file($tempFile,$targetFile);
			else
				throw new CHttpException(415, 'The file already exist.');
		}

		else
			throw new CHttpException(415, 'Internal problem, sorry.');

		/*Multiples archivos
		 foreach ($_FILES["pictures"]["error"] as $key => $error) {
			if ($error == UPLOAD_ERR_OK) {
				$tmp_name = $_FILES["pictures"]["tmp_name"][$key];
				$name = $_FILES["pictures"]["name"][$key];
				move_uploaded_file($tmp_name, "data/$name");
			}
		}*/
	}

	public function actionString_compressor()
	{
		$this->render('string_compressor');
	}

	public function actionIp_tools()
	{
		$this->render('ip_tools');
	}

	public function actionFancybox()
	{
		$this->render('fancybox');
	}

	public function actionTaskbar()
	{
		$this->render('taskbar');
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
	<link href="<?php echo Yii::app()->getBaseUrl(true) . '/scripts/jquery-ui/'; ?>css/ui-lightness/jquery-ui-1.10.4.custom.css" rel="stylesheet">
	<link rel="shortcut icon" href="<?php echo Yii::app()->request->baseUrl; ?>/images/favicon.ico" type="image/x-icon" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>

	<?php
		//Need to register this two cores in this order
		Yii::app()->clientScript->registerCoreScript('jquery');
		Yii::app()->clientScript->registerCoreScript('jquery.ui');
	?>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div>
	<!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu', array(
			'items' => array(
				array('label' => Yii::t('app','Home'), 'url' => array('/site/index')),
				array('label' => Yii::t('app','Map'), 'url' => array('/site/map')),
				array('label' => Yii::t('app','Social networks'), 'url' => array('/site/social')),
				array('label' => Yii::t('app','Array Order'), 'url' => array('/site/order_array')),
				array('label' => Yii::t('app','File uploader'), 'url' => array('/site/file_uploader')),
				array('label' => Yii::t('app','String compressor'), 'url' => array('/site/string_compressor')),
				array('label' => Yii::t('app','IP tools'), 'url' => array('/site/ip_tools')),
				array('label' => Yii::t('app','Fancybox'), 'url' => array('/site/fancybox')),
				array('label' => Yii::t('app','Taskbar'), 'url' => array('/site/taskbar')),
				array('label' => Yii::t('app','About'), 'url' => array('/site/page', 'view' => 'about','test' => '1011')),
				array('label' => Yii::t('app','Contact'), 'url' => array('/site/contact')),
				array('label' => Yii::t('app','Login'), 'url' => array('/site/login'), 'visible' => Yii::app()->user->isGuest),
				array('label' => Yii::t('app','Logout').' (' . Yii::app()->user->name . ')', 'url' => array('/site/logout'), 'visible' => !Yii::app()->user->isGuest),
				array('label' => '|'),
				array('label' => 'Gii', 'url' => array('/gii')),
				array('label' => '|'),
				array('label' => 'En', 'url' => array('','lang' => 'en')),
				array('label' => 'Es', 'url' => array('','lang' => 'es')),
			),
		)); ?>
	</div>

	<!-- mainmenu -->
	<?php if (isset($this->breadcrumbs)): ?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links' => $this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif ?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer"><?php echo Yii::t('app','Copyright {copy} {date} by {name}.{separator}All Rights Reserved.{separator}',array(
			'{copy}' => '&copy;','{date}' => date('Y'),'{separator}' => '<br />','{name}' => 'Edgar Cardona'
		)); ?>
		<?php echo Yii::powered(); ?>
	</div>
	<!-- footer -->

</div>
<!-- page -->

</body>
</html>