protected/controllers/HybridauthController.php
<?php

class HybridauthController extends Controller
{
    public function actionLogin()
    {
        if (!isset($_GET['provider']))
        {
            $this->redirect(array('/site/index'));
            return;
        }

        try
        {
            Yii::import('application.components.HybridAuthIdentity');
            $haComp = new HybridAuthIdentity();
            if (!$haComp->validateProviderName($_GET['provider']))
                throw new CHttpException ('500', 'Invalid Action. Please try again.');

            $haComp->adapter = $haComp->hybridAuth->authenticate($_GET['provider']);

            if(isset($_GET['message']))
            {
                $haComp->adapter->setUserStatus( $_GET['message'] );
                return;
            }

            else
            {
                $haComp->userProfile = $haComp->adapter->getUserProfile();
                $haComp->login();

                $this->redirect(SessionManager::GET_SESSION('lastUrl'));
            }
        }
        catch (Exception $e)
        {
            //process error message as required or as mentioned in the HybridAuth 'Simple Sign-in script' documentation
            throw new CHttpException(403, $e);
            return;
        }
    }

    public function actionSocialLogin()
    {
        Yii::import('application.components.HybridAuthIdentity');
        $path = Yii::getPathOfAlias('ext.hybridauth');
        require_once $path . '/index.php';
    }

    public function actionShareContent()
    {
        try
        {
            Yii::import('application.components.HybridAuthIdentity');
            $haComp = new HybridAuthIdentity();
            if (!$haComp->validateProviderName($_GET['provider']))
                throw new CHttpException ('500', 'Invalid Action. Please try again.');

            $haComp->adapter = $haComp->hybridAuth->authenticate($_GET['provider']);
            $haComp->userProfile = $haComp->adapter->getUserProfile();

            $haComp->login();
            $this->redirect(array('site/index?success=1'));
        }
        catch (Exception $e)
        {
            //process error message as required or as mentioned in the HybridAuth 'Simple Sign-in script' documentation
            throw new CHttpException(403, $e);
            return;
        }
    }

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		if(isset(Yii::app()->user->type) && Yii::app()->user->type === 'social_user')
			$redirectUrl = Yii::app()->session['lastUrl'];

		else
			$redirectUrl = Yii::app()->homeUrl;

		Yii::app()->user->logout();

		$this->redirect($redirectUrl);
	}

	public function actionMap()
	{
		$this->render('map',array(
			'mapOptions' => array(
				'id' => 'map',
				'defaultUI' => json_encode(false),
				'addMarkers' => json_encode(array('enabled' => true,'limit' => 4,'deleteOnClick' => true,'centerOnClick' => true,'traceRoute' => true)),
				'markersData' => json_encode(array(
					'abc' => array(
						'title' => 'hola',
						'x' => '-25.352393',
						'y' => '131.044923',
						'message' => 'que paso!?',
						'image' => Yii::app()->getBaseUrl(true).'/images/site/marker2.png',
						'shape' => array('coord' => array(14,32,17,32,18,18,24,11,24,6,19,0,12,0,7,6,7,11,13,17,14,32),'type' => 'poly')
					),
					'def' => array(
						'title' => 'otro hola',
						'x' => '-25.363882',
						'y' => '131.044922',
						'message' => 'que pasaaaaaaaoooooooo!!',
						'image' => Yii::app()->getBaseUrl(true).'/images/site/marker1.png',
						'shape' => array('coord' => array(13,32,26,20,26,2,0,1,0,20,13,32),'type' => 'poly')
					)
				))
			),
		));
	}

	public function actionSocial()
	{
		$this->render('social');
	}

	public function actionOrder_Array()
	{
		$data = array(array('valor' => 10),array('valor' => 50),array('valor' => 75),array('valor' => 5),array('valor' => 100));
		$dataSorted = ArrayTools::ORDER_ARRAY($data,'valor');
		$dataSortedInv = ArrayTools::ORDER_ARRAY($data,'valor',true);
		$this->render('order_array',array('data' => $data,'dataSorted' => $dataSorted,'dataSortedInv' => $dataSortedInv));
	}

	public function actionFile_uploader()
	{
		$uploaderConfig = array();
		$uploaderConfig['id'] = 'fileupload';
		$uploaderConfig['id_js'] = '#'.$uploaderConfig['id'];
		$uploaderConfig['id_progress'] = 'progress';
		$uploaderConfig['id_js_progress'] = '#'.$uploaderConfig['id_progress'];

		$this->render('file_uploader',array(
			'uploaderConfig' => $uploaderConfig
		));
	}

	public function actionUpload()
	{
		$ds = DIRECTORY_SEPARATOR;
		$storeFolder = 'uploads';
		$fileMaxSize = 10485760; //10MiB
		$fileMaxSizeString = (string)($fileMaxSize/1024/1024).' MiB';

		if (!empty($_FILES)) {

			if($_FILES['file']['type'] != image_type_to_mime_type(IMAGETYPE_JPEG) && $_FILES['file']['type'] != image_type_to_mime_type(IMAGETYPE_PNG))
				throw new CHttpException(415, 'Unsupported Media Type. ('.$_FILES['file']['type'].')');

			if($_FILES['file']['size'] > $fileMaxSize)
				throw new CHttpException(415, 'The file is too large to upload (Max '.$fileMaxSizeString.').');

			$tempFile = $_FILES['file']['tmp_name'];
			$targetPath = Yii::getPathOfAlias('local') . $ds. $storeFolder . $ds;
			$targetFile =  $targetPath. $_FILES['file']['name'];
			if(!file_exists($targetFile))
				move_uploaded_file($tempFile,$targetFile);
			else
				throw new CHttpException(415, 'The file already exist.');
		}

		else
			throw new CHttpException(415, 'Internal problem, sorry.');

		/*Multiples archivos
		 foreach ($_FILES["pictures"]["error"] as $key => $error) {
			if ($error == UPLOAD_ERR_OK) {
				$tmp_name = $_FILES["pictures"]["tmp_name"][$key];
				$name = $_FILES["pictures"]["name"][$key];
				move_uploaded_file($tmp_name, "data/$name");
			}
		}*/
	}

	public function actionString_compressor()
	{
		$this->render('string_compressor');
	}

	public function actionIp_tools()
	{
		$this->render('ip_tools');
	}

	public function actionFancybox()
	{
		$this->render('fancybox');
	}

	public function actionTaskbar()
	{
		$this->render('taskbar');
	}
}

protected/views/site/contact.php
<?php
/* @var $this SiteController */
/* @var $model ContactForm */
/* @var $form CActiveForm */

$this->pageTitle=Yii::app()->name . ' - Contact Us';
$this->breadcrumbs=array(
	'Contact',
);
?>

<h1><?php echo Yii::t('app','Contact Us'); ?></h1>

<?php if(Yii::app()->user->hasFlash('contact')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('contact'); ?>
</div>

<?php else: ?>

<p>
<?php echo Yii::t('app','If you want to give me a feedback please do it here. Thank you.'); ?>
</p>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'contact-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note"><?php echo Yii::t('app','Fields with {required} are required.',array('{required}' => '<span class="required">*</span>')); ?></p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name'); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email'); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'subject'); ?>
		<?php echo $form->textField($model,'subject',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'subject'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'body'); ?>
		<?php echo $form->textArea($model,'body',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'body'); ?>
	</div>

	<?php if(CCaptcha::checkRequirements()): ?>
	<div class="row">
		<?php echo $form->labelEx($model,'verifyCode'); ?>
		<div>
		<?php $this->widget('CCaptcha'); ?>
		<?php echo $form->textField($model,'verifyCode'); ?>
		</div>
		<div class="hint"><?php echo Yii::t('app','Please enter the letters as they are shown in the image above.{separator}Letters are not case-sensitive.',array('{separator}' => '<br/>')) ?></div>
		<?php echo $form->error($model,'verifyCode'); ?>
	</div>
	<?php endif; ?>

	<div class="row buttons">
		<?php echo CHtml::submitButton(Yii::t('app','Submit')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php endif; ?>

protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2><?php echo Yii::t('app','Error'); ?> <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

protected/views/site/fancybox.php
<?php
	$cs = Yii::app()->getClientScript();

	$cs->registerScriptFile(Yii::app()->getBaseUrl(true) . '/scripts/js/site/fancybox.js', CClientScript::POS_END);
	$cs->registerScriptFile(Yii::app()->getBaseUrl(true) . '/scripts/js/fancybox/lib/jquery.mousewheel-3.0.6.pack.js', CClientScript::POS_END);
	$cs->registerScriptFile(Yii::app()->getBaseUrl(true) . '/scripts/js/fancybox/source/jquery.fancybox.pack.js?v=2.1.5', CClientScript::POS_END);

	$cs->registerCssFile(Yii::app()->getBaseUrl(true) . '/scripts/js/fancybox/source/jquery.fancybox.css?v=2.1.5', 'screen');
?>

<a class="fancybox" rel="group" href="<?php echo Yii::app()->getBaseUrl(true).'/images/site/marker1.png'; ?>"><img src="<?php echo Yii::app()->getBaseUrl(true).'/images/site/marker1.png'; ?>" alt="" /></a>
<a class="fancybox" rel="group" href="<?php echo Yii::app()->getBaseUrl(true).'/images/site/marker2.png'; ?>"><img src="<?php echo Yii::app()->getBaseUrl(true).'/images/site/marker2.png'; ?>" alt="" /></a>

protected/views/site/file_uploader.php
<?php
	/**
	 * Jquery File uploader wrapper
	 * User: Edgar
	 * Date: 4/14/14
	 * Time: 9:32 AM
	 *
	 * @var $uploaderConfig array
	 * @var $this SiteController
	 */

	$cs = Yii::app()->getClientScript();

	$cs->registerCssFile(Yii::app()->getBaseUrl(true) . '/css/site/file_uploader.css');
	$cs->registerCssFile(Yii::app()->getBaseUrl(true) . '/css/dropzone/dropzone.css');

	$cs->registerScriptFile(Yii::app()->getBaseUrl(true) . '/scripts/js/dropzone/dropzone.js', CClientScript::POS_END);
	$cs->registerScriptFile(Yii::app()->getBaseUrl(true) . '/scripts/js/site/file_uploader.js', CClientScript::POS_END);
?>

<script>
	var uploaderID = '<?php echo $uploaderConfig['id_js']; ?>';
	var uploaderProgressID = '<?php echo $uploaderConfig['id_js_progress']; ?>';
</script>

<p><?php echo Yii::t('app', 'File uploader using {ext}', array('{ext}' => 'JQuery File Upload API')); ?></p>

<form id="my-awesome-dropzone" action="<?php echo $this->createUrl('upload'); ?>" class="dropzone" enctype="multipart/form-data">
	<div class="fallback"> <!-- this is the fallback if JS isn't working -->
		<input name="file" type="file" multiple />
	</div>
</form>

protected/views/site/index.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
?>

<h1><?php echo Yii::t('app','Welcome to {name}',array('{name}' => '<i>'.CHtml::encode(Yii::app()->name).'</i>')); ?></h1>

<p><?php echo Yii::t('app','Compilation of global functions to make life easier.'); ?></p>

protected/views/site/ip_tools.php
<?php
/**
 * Created by PhpStorm.
 * User: Edgar
 * Date: 8/19/14
 * Time: 12:01 PM
 */
?>

<div>
	<p><?php echo Yii::t('app','User IP'); ?></p>
	<pre><?php echo IpTools::GET_USER_IP(); ?></pre>
	<p><?php echo Yii::t('app','Format IP to database') ?></p>
	<pre><?php echo IpTools::GET_USER_IP().' -> '.IpTools::GET_USER_IP_BDD_FORMAT(); ?></pre>
	<p><?php echo Yii::t('app','Get the IP information') ?></p>
	<pre><?php print_r(IpTools::GET_IP_DATA_EXTERNAL_SOURCE(false)); ?></pre>
</div>

protected/views/site/login.php
<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form CActiveForm  */

$this->pageTitle=Yii::app()->name . ' - Login';
$this->breadcrumbs=array(
	'Login',
);
?>

<h1><?php echo Yii::t('app','Login'); ?></h1>

<p><?php echo Yii::t('app','Please fill out the following form with your login credentials:') ?></p>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note"><?php echo Yii::t('app','Fields with {required} are required.',array('{required}' => '<span class="required">*</span>')); ?></p>

	<div class="row">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>
	</div>

	<div class="row rememberMe">
		<?php echo $form->checkBox($model,'rememberMe'); ?>
		<?php echo $form->label($model,'rememberMe'); ?>
		<?php echo $form->error($model,'rememberMe'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton(Yii::t('app','Login')); ?>
	</div>

<?php $this->endWidget(); ?>
</div><!-- form -->

protected/views/site/map.php
<?php
	/**
	 * Google maps wrapper
	 * User: Edgar
	 * Date: 4/14/14
	 * Time: 9:32 AM
	 *
	 * @var $mapOptions array
	 */

	$cs = Yii::app()->getClientScript();
	$cs->registerScriptFile(Yii::app()->getBaseUrl(true) . '/scripts/js/site/map.js', CClientScript::POS_END);
	$cs->registerScriptFile("https://maps.googleapis.com/maps/api/js?key=AIzaSyBlUd3oWqgl00-XFF1uO1fdsaaZzJ-y5Gg&sensor=false", CClientScript::POS_END);
?>

<script>
	var markersData = <?php echo isset($mapOptions['markersData']) ? $mapOptions['markersData'] : "null"; ?>;
	var addMarkers = <?php echo isset($mapOptions['addMarkers']) ? $mapOptions['addMarkers'] : "null"; ?>;
	var defaultUI = <?php echo isset($mapOptions['defaultUI']) ? $mapOptions['defaultUI'] : "null"; ?>;
    var maxMarkersMsj = "<?php echo "yes" ?>";
</script>

<p><?php echo Yii::t('app','Helper for Google map API') ?></p>

<div id="<?php if(isset($mapOptions['id'])) echo $mapOptions['id']; ?>" style="width: 600px; height: 480px; margin: 20px auto"></div>

protected/views/site/order_array.php
<?php
/**
 * @var $data array
 * @var $dataSorted array
 * @var $dataSortedInv array
 */
?>

<p><?php echo Yii::t('app','Function to sort arrays, using binary sort.'); ?></p>

<div class="well">
	<p><?php echo Yii::t('app','Before order'); ?></p>
	<?php DataShow::WALK_ARRAY($data); ?>
</div>

<div class="well">
	<p><?php echo Yii::t('app','After order'); ?></p>
	<?php DataShow::WALK_ARRAY($dataSorted); ?>
</div>

<div class="well">
	<p><?php echo Yii::t('app','After order inverted'); ?></p>
	<?php DataShow::WALK_ARRAY($dataSortedInv); ?>
</div>

protected/views/site/social.php
<?php
	/**
	 * Created by PhpStorm.
	 * User: Edgar
	 * Date: 4/6/14
	 * Time: 3:46 PM
	 */
?>

<p><?php echo Yii::t('app','Social Hub using hybridauth API'); ?></p>

<div class="zocial-container">
	<div class="zocial-wrapper">
		<a class="zocial google" href="<?php echo $this->createUrl('/hybridauth/login', array('provider' => 'google')); ?>"></a>
		<a class="zocial facebook" href="<?php echo $this->createUrl('/hybridauth/login', array('provider' => 'facebook')); ?>"></a>
	</div>
</div>
<div class="clear"></div>

protected/views/site/string_compressor.php
<div class="wrapper-block">
	<?php
		/**
		 * Google maps wrapper
		 * User: Edgar
		 * Date: 4/14/14
		 * Time: 9:32 AM
		 *
		 * @var $mapOptions array
		 */

		$cad = "191,294,189,299,193,309,193,318,195,324,195,342,196,343,196,346,195,348,198,355,197,367,194,378,198,386,197,389,197,396,197,398,196,408,196,414,196,424,199,435,206,450,208,453,214,457,221,459,226,461,241,462,242,458,241,456,238,455,234,455,233,449,231,446,227,443,223,443,220,445,217,444,215,440,214,439,213,440,210,438,209,434,212,430,212,427,211,426,212,423,212,421,213,408,209,408,210,406,207,402,207,397,206,393,206,387,206,384,207,382,206,379,204,375,205,372,206,371,206,368,205,365,206,364,207,361,206,359,205,356,202,352,202,347,202,337,204,333,206,331,204,328,204,326,203,321,207,318,207,313,204,313,200,308,198,304,198,301,191,294";
		echo $cad;
		$cadComp = gzcompress($cad);
		echo "<br>";
		echo $cadComp;
		$cadUncomp = gzuncompress($cadComp);
		echo "<br>";
		echo $cadUncomp;
	?>
</div>

protected/views/site/taskbar.php
<?php
$cs = Yii::app()->getClientScript();
$cs->registerCssFile(Yii::app()->getBaseUrl(true) . '/css/site/taskbar.css');
?>

<div id="taskbar">
    <div id="taskbar-content">
        <?php for ($i = 1; $i <= 8; $i++): ?>
            <div class="taskbar-icon float-left">
                <a class="taskbar-link" href="#"><?php echo Yii::t('app', 'Test {n}', array('{n}' => $i)); ?></a>
            </div>
        <?php endfor; ?>
        <div class="clear"></div>
    </div>
</div>